### ISSUE TITLE
Updated Priority Now It Won't show on the cards

### ISSUE THREAD

**Issue by ablajoie** [m-radzikowski/youtrack-issue-cards-printer#6] opened 2018-08-11 02:06 UTC
I had updated the Priority options to have more than the 1,2,3,4... then it didn't show on the Cards. I Removed the Extension and Added it again but even with the Original 1,2,3,4 they don't show on the cards? Like this a lot!

**Comment by m-radzikowski** [comment] 2018-08-19 10:40
Hi,
I tried, but I'm unable to reproduce your problem. Could you attach screenshot of project fields settings with priority field selected? Just like this one:
![yt-fields-settings](https://user-images.githubusercontent.com/4042673/44307979-eb2b8380-a3ac-11e8-8b48-e986c340de13.png)

**Comment by m-radzikowski** [comment] 2019-03-19 12:21
Closing as I'm unable to reproduce the issue, please reopen with more details if issue still occurs.

**Closed by m-radzikowski** 2019-03-19 12:21 UTC
Labels: bug
